steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/vipa0120/DemoRepo.git']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}:${_SHORT_SHA}', '. Dockerfile']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}:${_SHORT_SHA}']

options:
  logging: CLOUD_LOGGING_ONLY  # Or use NONE if you don't want any logging.
  
substitutions:
  _IMAGE_NAME: 'gke-image'
  _SHORT_SHA: 'v2.0'
  _PROJECT_ID: 'test-ci-cd-437808'
