steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/vipa0120/DemoRepo.git']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}:$SHORT_SHA', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}:$SHORT_SHA']


  substitutions:
   _IMAGE_NAME: gke-image
   _SHORT_SHA: v2.0
   _PROJECT_ID: test-ci-cd-437808
