steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/vipa0120/DemoRepo.git']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}:${_SHORT_SHA}', './DemoRepo/']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}:${_SHORT_SHA}']
  
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
    'set',
    'image',
    'deployment',
    'cicd-deploy',
    'gke-image-sha256-1=gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}:${_SHORT_SHA}'
    ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-south1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cicd-cluster'
    
options:
  logging: CLOUD_LOGGING_ONLY  # Or use NONE if you don't want any logging.
  
substitutions:
  _IMAGE_NAME: 'gke-image'
  _SHORT_SHA: 'v100'
  _PROJECT_ID: 'test-ci-cd-437808'
