steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/vipa0120/DemoRepo.git']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t' 'grc.io/${PROJECT_ID}/${_IMAGE_NAME}:$SHORT_SHA', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'grc.io/${PROJECT_ID}/${_IMAGE_NAME}:$SHOER_SHA']
