# ============== DEPLOYMENT VARIABLES ============================
INTERNAL_TLS_ENABLED: false
MONITORING_ENABLED: false
CLOUD_TOPOLOGY_KEY: kubernetes.io/hostname
READONLY_CONTAINER_FILE_SYSTEM_ENABLED: false

keyManager:
  readinessProbe:
    initialDelaySeconds: 5
    timeoutSeconds: 30
  livenessProbe:
    initialDelaySeconds: 5
    timeoutSeconds: 30

# ============== SERVICE VARIABLES ============================
LOG_LEVEL: "info"

TRACING_ENABLED: false
TRACING_HOST: 'nc-diagnostic-agent'
TRACING_SAMPLER_RATELIMITING: 10

M2MType: 'keycloak'
VAULT_INTEGRATION: false
