apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{ .Values.SERVICE_NAME }}'
  namespace: '{{ .Values.NAMESPACE }}'
---
  {{ if and ( eq .Values.PAAS_PLATFORM "OPENSHIFT" ) ( eq .Values.PAAS_VERSION "v1.5" ) }}
apiVersion: v1
  {{ else }}
apiVersion: rbac.authorization.k8s.io/v1
  {{ end }}
kind: Role
metadata:
  name: '{{ .Values.SERVICE_NAME }}-serviceaccounts-role'
  namespace: '{{ .Values.NAMESPACE }}'
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - watch
---
  {{ if and ( eq .Values.PAAS_PLATFORM "OPENSHIFT" ) ( eq .Values.PAAS_VERSION "v1.5" ) }}
apiVersion: v1
  {{ else }}
apiVersion: rbac.authorization.k8s.io/v1
  {{ end }}
kind: RoleBinding
metadata:
  name: '{{ .Values.SERVICE_NAME }}-serviceaccounts-binding'
  namespace: '{{ .Values.NAMESPACE }}'
roleRef:
  name: '{{ .Values.SERVICE_NAME }}-serviceaccounts-role'
  {{ if and ( eq .Values.PAAS_PLATFORM "OPENSHIFT" ) ( eq .Values.PAAS_VERSION "v1.5" ) }}
  namespace: '{{ .Values.NAMESPACE }}'
  {{ else }}
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  {{ end }}
subjects:
- kind: ServiceAccount
  name: '{{ .Values.SERVICE_NAME }}'
  namespace: '{{ .Values.NAMESPACE }}'
---
  {{ if and ( eq .Values.PAAS_PLATFORM "OPENSHIFT" ) ( eq .Values.PAAS_VERSION "v1.5" ) }}
apiVersion: v1
  {{ else }}
apiVersion: rbac.authorization.k8s.io/v1
  {{ end }}
kind: Role
metadata:
  name: '{{ .Values.SERVICE_NAME }}-secrets-role'
  namespace: '{{ .Values.NAMESPACE }}'
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - watch
      - delete
---
  {{ if and ( eq .Values.PAAS_PLATFORM "OPENSHIFT" ) ( eq .Values.PAAS_VERSION "v1.5" ) }}
apiVersion: v1
  {{ else }}
apiVersion: rbac.authorization.k8s.io/v1
  {{ end }}
kind: RoleBinding
metadata:
  name: '{{ .Values.SERVICE_NAME }}-secrets-binding'
  namespace: '{{ .Values.NAMESPACE }}'
roleRef:
  name: '{{ .Values.SERVICE_NAME }}-secrets-role'
  {{ if and ( eq .Values.PAAS_PLATFORM "OPENSHIFT" ) ( eq .Values.PAAS_VERSION "v1.5" ) }}
  namespace: '{{ .Values.NAMESPACE }}'
  {{ else }}
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  {{ end }}
subjects:
  - kind: ServiceAccount
    name: '{{ .Values.SERVICE_NAME }}'
    namespace: '{{ .Values.NAMESPACE }}'